version: "0.1.35.{build}"
install:
  - ps: Invoke-WebRequest http://kitcreator.rkeene.org/kits/73e51976aa01502eb5b4365a35ac35ad38f46414/tclkit.exe -OutFile tclsh.exe
build_script:
  - cmd: build-mingw.cmd /batch
test_script:
  - cmd: picol.exe test.pcl
after_build:
  - cmd: copy picol.exe picol_debug.exe
  - cmd: strip picol.exe
artifacts:
  - path: picol.exe
  - path: picol_debug.exe
