version: "{build}"
install:
  - ps: Invoke-WebRequest http://kitcreator.rkeene.org/kits/787d0ae3ea5eac8cf68d6b9e766b0fda0a3579ea/tclkit.exe -OutFile tclsh.exe
build_script:
  - cmd: set default_path=%PATH%
  - cmd: set source_version=%APPVEYOR_REPO_COMMIT:~0,10%_%APPVEYOR_REPO_TAG_NAME%

  - cmd: build-mingw.cmd /batch
  - cmd: copy picolsh.exe picolsh_%source_version%_mingw.exe
  - cmd: copy picolsh.exe picolsh_%source_version%_mingw_debug.exe
  - cmd: strip picolsh_%source_version%_mingw.exe
  - cmd: make clean

  - cmd: set PATH=%default_path%

  - cmd: build-msvc.cmd /batch /version:12.0
  - cmd: copy picolsh.exe picolsh_%source_version%_msvc.exe
test_script:
  - cmd: picolsh_%source_version%_mingw.exe test.pcl
  - cmd: picolsh_%source_version%_msvc.exe test.pcl
artifacts:
  - path: picolsh_%source_version%_mingw.exe
  - path: picolsh_%source_version%_mingw_debug.exe
  - path: picolsh_%source_version%_msvc.exe
